name: document_scanner_flutter
description: A Flutter plugin for Android & iOS document scanning and auto-detection.
version: 0.3.0
homepage: https://github.com/ishaquehassan/document_scanner_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1 # Updated to latest version
  photo_view: ^0.15.0 # Updated to latest version
  path_provider: ^2.0.15 # Already up-to-date, kept unchanged

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0 # Added for maintaining linting rules and code consistency
  build_runner: ^2.4.6 # Added for generating code, if needed

flutter:
  plugin:
    platforms:
      android:
        package: com.document.scanner.flutter.document_scanner_flutter
        pluginClass: DocumentScannerFlutterPlugin
      ios:
        pluginClass: DocumentScannerFlutterPlugin

  assets:
    # Specify assets if needed, for example:
    # - images/document_placeholder.png
